### ISSUE TITLE
Add .htaccess with wp-admin redirect.

### ISSUE THREAD

**Issue by vinkla** [vinkla/wordpress-boilerplate#12]
Add a `.htaccess` file to the webroot. The user currently needs to go through */wordpress/wp-admin* to visit the admin area. Lets add a `.htaccess` file that redirects the user to the correct URL.

**Comment by fredericpfisterer** [comment]
Hello there,

I still have to go through /wordpress/wp-admin to visit the admin area. Can you point me in the right direction to solve this ?

Thanks :-)

**Comment by vinkla** [comment]
If you visit `/wp-admin` does it redirect you to `/wordpress/wp-admin`?

**Comment by fredericpfisterer** [comment]
It does not. Know that I’m using Laravel valet and I installed your driver.

**Comment by vinkla** [comment]
Hmm, I pushed an update to the Valet driver a couple of days ago. Maybe try updating.

**Comment by fredericpfisterer** [comment]
That's the one I'm using. It works fine on my production server but not on my local machine using laravel valet.

Any ideas what could be the issue ?

Thanks

**Comment by vinkla** [comment]
I'm also running the Valet driver on macOS without any issues. This could be an issue with plugins which update the permalinks. I've had problems with e.g. Polylang and Valet in the past.

**Comment by fredericpfisterer** [comment]
I managed to fix it with this :

`if (strpos($uri, '/wordpress/wp-admin/') === 0){
            $_SERVER['PHP_SELF'] = $uri;
        }`

**Comment by fredericpfisterer** [comment]
Maybe it has to do with your version of Laraval Valet ? I'm using 2.0.6

**Comment by vinkla** [comment]
Hmm, I'm using 2.0.6 as well and it works fine. Glad it worked out for you!
