### ISSUE TITLE
init.php should be renamed to index.php

### ISSUE THREAD

**Issue by puredazzle** [vinkla/wordpress-boilerplate#43]
Init.php sometimes (most of the time) doesn't get uploaded to the server. Tested on Transmit 4.4.8 and MediaTemple grid-server.

**Comment by vinkla** [comment]
In `wp-content/themes/boilerplate/library`?

**Comment by puredazzle** [comment]
As we discussed index.php for library should be better?

**Comment by vinkla** [comment]
I'll rename it.
